In [2]:
!pip install rdflib
!pip install pandas

Requirement already satisfied: rdflib in /home/noob/.local/lib/python3.8/site-packages (6.0.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from rdflib) (45.2.0)
Requirement already satisfied: isodate in /home/noob/.local/lib/python3.8/site-packages (from rdflib) (0.6.0)
Requirement already satisfied: pyparsing in /usr/lib/python3/dist-packages (from rdflib) (2.4.6)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from isodate->rdflib) (1.14.0)
Requirement already satisfied: pandas in /home/noob/.local/lib/python3.8/site-packages (1.3.3)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3/dist-packages (from pandas) (2019.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/noob/.local/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /home/noob/.local/lib/python3.8/site-packages (from pandas) (1.21.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7.3->pandas) (1.14.0)

In [15]:
from rdflib import URIRef, BNode, Literal, Namespace, Graph
from rdflib.namespace import FOAF,  DCTERMS, XSD, RDF, SDO
import pandas as pd

In [16]:
df = pd.read_csv('prod.csv', index_col=False)
df

,Product id,Product Name,RAM (in GB),SDD (in GB),Price (in INR),Processor,ScreenSize(in inch)
0,1,Acer Aspire,4,256,31000,i5,15.5
1,2,Macbook,8,128,87000,i3,13.3
2,3,Lenevo notebook,8,512,47000,Ryzen-3,14.0
3,4,Acer Notebook,16,256,35000,i3,15.5
4,5,Acer NItro,16,256,87000,i7,17.0
5,6,HP,8,512,40000,Ryzen-3,14.0
6,7,HP Chromebook,8,64,21000,Dual Core,11.0
7,8,Asus Vivobook,4,256,27999,i3,15.5
8,9,Asus Chromebook,8,64,21000,Dual Core,11.0
9,10,Dell,4,512,59000,i5,15.3
10,11,Macbook,16,512,111700,i5,13.3

In [17]:
g = Graph()
ex = Namespace('https://www.example.org/')
id = ex['id']
productID = ex['hasProductID']
name  = ex['name']
ram  = ex['hasRAM']
ssd = ex['hasSSD']
price = ex['hasPrice']
processor = ex['hasProcessor']
screen = ex['hasScreenSize']

In [ ]:
df['Product id']

In [ ]:
import rdflib.tools.csv2rdf as rdfc
rdfc.CSV2RDF()